package fatec.estudo.projetohash;

public enum BenchmarkEnum {
    NORDPASS_BCRYPT, // NORDPASS 200 PASSWORD LIST
    NORDPASS_SCRYPT,
    NORDPASS_PBKDF2,
    NORDPASS_ARGON2,

    PASSWORD10K_BCRYPT, // 10K PASSWORD LIST
    PASSWORD10K_SCRYPT,
    PASSWORD10K_PBKDF2,
    PASSWORD10K_ARGON2,

    RANDOM20PASSWORDLENGTH8_BCRYPT, // RANDOMLY GENERATED 20 PASSWORDS OF 8 CHARACTERS
    RANDOM20PASSWORDLENGTH8_SCRYPT,
    RANDOM20PASSWORDLENGTH8_PBKDF2,
    RANDOM20PASSWORDLENGTH8_ARGON2,

    RANDOM20PASSWORDLENGTH12_BCRYPT, // RANDOMLY GENERATED 20 PASSWORDS OF 12 CHARACTERS
    RANDOM20PASSWORDLENGTH12_SCRYPT,
    RANDOM20PASSWORDLENGTH12_PBKDF2,
    RANDOM20PASSWORDLENGTH12_ARGON2,

    RANDOM20PASSWORDLENGTH15_BCRYPT, // RANDOMLY GENERATED 20 PASSWORDS OF 15 CHARACTERS
    RANDOM20PASSWORDLENGTH15_SCRYPT,
    RANDOM20PASSWORDLENGTH15_PBKDF2,
    RANDOM20PASSWORDLENGTH15_ARGON2,

}
